### ISSUE TITLE
Upload to a CDN provider

### ISSUE THREAD

**Issue by eryc-cc** [gammesB/tiny-slider-withfixes#2]
__Issue description__:  
Upload the new version to a CDN provider, and update the README files, so that people can use this version of the Tiny Slider. Seems like the original repo is not maintained anymore.

Not sure this is an easy thing to do.

**Comment by gammesB** [comment]
What do you mean with update the readme?
I am not planning on hosting the file, but people can just download the file from the dist folder or rebuild it themselfs.
the file is also directly accesible through github:
https://gammesb.github.io/tiny-slider-withfixes/dist/min/tiny-slider.js
https://gammesb.github.io/tiny-slider-withfixes/dist/tiny-slider.css

**Comment by eryc-cc** [comment]
Nevermind, thanks!
